[WIP] ABC v6 export
haekb/io_scene_lithtech pull request #25
Opened 2021-02-14 07:20 UTC by Five-Damned-Dollarz

Still very much WIP. No vertex animation yet, normals may export wrong.

2021-03-04 06:15 UTC, Five-Damned-Dollarz commented
This should be complete now, unless I've somehow missed a huge bug.
There's at least one derpy workaround in there, and the export process could probably be optimized, but as far as I can see it works great. Importing then exporting an original game file looks virtually identical (except for bounding boxes, which I try to create as best I can from the geometry).
The one thing I'm concerned about is node bounding boxes, since I haven't found any debug commands in Blood 2 to display them on models, I can't be sure they're correct. We can make changes easily enough in the future if it becomes clear they need fixing.

2021-03-14 03:29 UTC, haekb requested changes
At some point github jammed up because I was adding too many suggestions. Please use spaces (and fix the ones I didn't suggest toooo!) 

Aside from that, I didn't notice any breakage from abc v12 -> lta export. So it's good to go.

2021-03-14 03:29 UTC, haekb commented on src/abc.py
> +        self.normal=Vector()
```suggestion
        self.normal = Vector()
```

2021-03-14 03:29 UTC, haekb commented on src/abc.py
> +        self.bounds_min=Vector()
```suggestion
        self.bounds_min = Vector()
```

2021-03-14 03:29 UTC, haekb commented on src/abc.py
> +        self.bounds_max=Vector()
```suggestion
        self.bounds_max = Vector()
```

2021-03-14 03:29 UTC, haekb commented on src/abc.py
> +        self.bounds_min=Vector()
```suggestion
        self.bounds_min = Vector()
```

2021-03-14 03:29 UTC, haekb commented on src/abc.py
> +        self.bounds_max=Vector()
```suggestion
        self.bounds_max = Vector()
```

2021-03-14 03:29 UTC, haekb commented on src/abc.py
> +        self.vertex_deformation_bounds=dict()
```suggestion
        self.vertex_deformation_bounds = dict()
```

2021-03-14 03:29 UTC, haekb commented on src/abc.py
> +        self.is_vertex_animation = 0
Thanks!

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                face.normal=polygon.normal
```suggestion
                face.normal = polygon.normal
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                            node.bounds_min=Vector((min(node.bounds_min.x, vertex.location.x), min(node.bounds_min.y, vertex.location.y), min(node.bounds_min.z, vertex.location.z)))
```suggestion
                            node.bounds_min = Vector((min(node.bounds_min.x, vertex.location.x), min(node.bounds_min.y, vertex.location.y), min(node.bounds_min.z, vertex.location.z)))
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                            node.bounds_max=Vector((max(node.bounds_min.x, vertex.location.x), max(node.bounds_min.y, vertex.location.y), max(node.bounds_min.z, vertex.location.z)))
```suggestion
                            node.bounds_max = Vector((max(node.bounds_min.x, vertex.location.x), max(node.bounds_min.y, vertex.location.y), max(node.bounds_min.z, vertex.location.z)))
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                keyframe.bounds_min=Vector(mesh_object.bound_box[0]) # will using mesh_object here break if there's multiple mesh
```suggestion
                keyframe.bounds_min = Vector(mesh_object.bound_box[0]) # will using mesh_object here break if there's multiple mesh
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                keyframe.bounds_max=Vector(mesh_object.bound_box[6]) # objects using the same armature as a parent? DON'T DO THAT
```suggestion
                keyframe.bounds_max = Vector(mesh_object.bound_box[6]) # objects using the same armature as a parent? DON'T DO THAT
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                keyframe.bounds_max=Vector(mesh_object.bound_box[6]) # objects using the same armature as a parent? DON'T DO THAT
What's the significance of [6]? Please add some context, thanks.

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                bpy.context.scene.frame_set(time, subframe=time-floor(time))
```suggestion
                subframe_time = time - floor(time)
                bpy.context.scene.frame_set(time, subframe=subframe_time)
```
Makes it look a little cleaner

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +            if match(r"^d_", action.name): # skip any actions prefixed with "d_"; they're vertex animation lanes, we don't want them in the ABCv6 output
```suggestion
            # skip any actions prefixed with "d_"; they're vertex animation lanes, we don't want them in the ABCv6 output
            if match(r"^d_", action.name): 
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +            #    mesh.shape_keys.animation_data.action=md_action[0] if md_action else None
Do you still need this code?

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +            # this is horrible, but works
```suggestion
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                    bpy.context.scene.frame_set(time, subframe=time-floor(time))
```suggestion
                    subframe_time = time - floor(time)
                    bpy.context.scene.frame_set(time, subframe=subframe_time)
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +        vertex_tolerance=1e-5
```suggestion
        vertex_tolerance = 1e-5
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                animation.vertex_deformations=dict()
```suggestion
                animation.vertex_deformations = dict()
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                shape_keys=[shape_key for shape_key in mesh.shape_keys.key_blocks if shape_key.name.startswith(animation.name)]
```suggestion
                shape_keys = [shape_key for shape_key in mesh.shape_keys.key_blocks if shape_key.name.startswith(animation.name)]
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                    dirty_node=False
```suggestion
                    dirty_node = False
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                    animation.vertex_deformations[node]=[]
```suggestion
                    animation.vertex_deformations[node] = []
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                    node_vertices=[vertex_index for vertex_index, vertex in enumerate(model.pieces[0].lods[0].vertices) if vertex.weights[0].node_index==node_index]
```suggestion
                    node_vertices = [vertex_index for vertex_index, vertex in enumerate(model.pieces[0].lods[0].vertices) if vertex.weights[0].node_index == node_index]
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                    node.bounds_min=Vector((float("inf"), float("inf"), float("inf")))
```suggestion
                    node.bounds_min = Vector((float("inf"), float("inf"), float("inf")))
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                    node.bounds_max=Vector((float("-inf"), float("-inf"), float("-inf")))
```suggestion
                    node.bounds_max = Vector((float("-inf"), float("-inf"), float("-inf")))
```

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +                            #if not temp_vert.co==mesh.shape_keys.key_blocks[0].data[vertex_index].co:
You can probably remove this now

2021-03-14 03:29 UTC, haekb commented on src/builder.py
> +        anim_binding.extents = Vector((10, 10, 10))
Thanks

2021-03-14 11:35 UTC, Five-Damned-Dollarz commented
> At some point github jammed up because I was adding too many suggestions. Please use spaces (and fix the ones I didn't suggest toooo!)
> 
> Aside from that, I didn't notice any breakage from abc v12 -> lta export. So it's good to go.

I fixed as many as I could find, hopefully that's everything.

There is still one bug with the vertex animated node exporting with a slightly off rotation in rare animations, but it happens so infrequently in my experience that we could just make an issue for it, and hunt it later (with more information, hopefully, I have no idea where it comes from yet)

2021-03-14 20:49 UTC, haekb approved these changes

2021-03-14 20:49 UTC, haekb commented
Cool beans, thanks. If you could just open a github issue about that, so we don't forget, that'll be greeeeat.

2021-03-14 20:49 UTC, merged